export default {
    lie: 11,
    hang: 13,
    square: {
        "A": {
            8: "speed",
            9: "card",
            10: "event",
        },
        "B": {
            7: "damage",
            9: "enemy",
            11: "transport",
        },
        "C": {
            3: "recover",
            4: "gold",
            5: "start",
            6: "enemy",
            9: "shop",
            11: "gold",
        },
        "D": {
            2: "transport",
            9: "event",
            12: "recover",
        },
        "E": {
            1: "event",
            2: "damage",
            3: "attack",
            4: "card",
            5: "start",
            6: "speed",
            7: "event",
            8: "enemy",
            9: "attack",
            10: "damage",
            13: "enemy",
        },
        "F": {
            1: "upgrade",
            11: "shop",
            12: "gold",
            13: "start",
        },
        "G": {
            1: "event",
            2: "damage",
            3: "attack",
            4: "card",
            5: "start",
            6: "speed",
            7: "event",
            8: "enemy",
            9: "attack",
            10: "damage",
            13: "enemy",
        },
        "H": {
            2: "transport",
            9: "event",
            12: "recover",
        },
        "I": {
            3: "recover",
            4: "gold",
            5: "start",
            6: "enemy",
            9: "shop",
            11: "gold",
        },
        "J": {
            7: "damage",
            9: "enemy",
            11: "transport",
        },
        "K": {
            8: "speed",
            9: "card",
            10: "event",
        },
    },
}